<?php

declare(strict_types=1);

namespace App\Mcp\Tools;

use Illuminate\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;

final class SendMessageTool extends Tool
{
    /**
     * The tool's description.
     */
    protected string $description = <<<'MARKDOWN'
        Use this tool to send a message to the "Nuno Nation Chat" server.
        MARKDOWN;

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        $request->validate([
            'name' => 'string|min:1|max:50|required',
            'content' => 'string|min:1|max:500|required',
        ]);

        $name = $request->string('name')->value();
        $content = $request->string('content')->value();

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()
                ->min(1)
                ->max(50)
                ->required()
                ->description(<<<'MARKDOWN'
                    The name of the user sending the message.

                    Don't use "User", or "Assistant", or "Claude", or "GPT", or "AI", or "Bot".

                    IMPORTANT: Ask the user for their first name if you don't know it.
                    MARKDOWN),
            'content' => $schema->string()
                ->min(1)
                ->max(500)
                ->required(),
        ];
    }
}
